apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: phpmyadmin
  name: phpmyadmin
spec:
  containers:
  - image: phpmyadmin/phpmyadmin:latest
    name: phpmyadmin
    env:
    - name: PMA_HOST
      value: "mysql-svc.default.svc.cluster.local"
      name: PMA_PORT
      value: "3306"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
